{% set version = "1.24.11" %}
{% set gst_version = "1.24.11" %}

package:
  name: gstreamer-bundle
  version: "{{ version }}"

build:
  noarch: generic
  number: 0

requirements:
  run:
    - pygobject
    - gst-python =={{ gst_version }}
    - gst-libav =={{ gst_version }}
    - gstreamer =={{ gst_version }}
    - gst-plugins-base =={{ gst_version }}
    - gst-plugins-good =={{ gst_version }}
    - gst-plugins-bad =={{ gst_version }}
    - gst-plugins-ugly =={{ gst_version }}

about:
  home: https://github.com/open-world-agents/open-world-agents
  license: MIT
  summary: Meta-package with GStreamer-related dependencies for Open World Agents
